### ISSUE TITLE
Publish wait improvement

### ISSUE THREAD

**Issue by chriskl** [forcedotcom/sfdx-bitbucket-package#5]
How about instead of the nasty sleep 5m that burns Bitbucket Pipeline minutes, remove it and change the force:package:install line to use --publishwait 5 instead?

**Comment by douglascayers** [comment]
Good eye, @chriskl! Would you like to submit a PR with the change? I'm assuming you probably have already tested the bitbucket pipeline change using the package install command with `--publishwait 10 --wait 10` arguments?

**Comment by chriskl** [comment]
Hah, I'm just a bit lazy with doing PRs :) I have tested it fine on my own version of this pipeline, so I'll submit an untested PR to add it back to yours then.
